services:
  db:
    build: ./
    image: mssql
    volumes:
        - ./container_db:/var/opt/mssql/data
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: P@ssword123
    ports:
        - 6000:1433
    container_name: db